#!/bin/sh

. ./docker.sh

DAHDI="libnewt dahdi-linux-complete dahdi-complete"
ASTERISK="libpri asterisk-sounds-en"
ASTERISK_8="$ASTERISK asterisk-1.8"
ASTERISK_13="$ASTERISK libjansson pjproject asterisk-13"
UPDATES="production-tests"
PRODTEST="bx33-utils digium-env hwtest perl-production-libs $UPDATES"
TC_4="openssl squashfs-tools usbutils"
TC_7=""
VIRTUAL_PACKAGES="$TC_7"
PACKAGES="$UPDATES"

if [ "$1" = "-N" ]; then
  PACKAGES="$VIRTUAL_PACKAGES $DAHDI $ASTERISK_13 $PRODTEST"
fi

build_packages $PACKAGES
remaster prodtest.cfg
